fix: address follow-up review feedback

diff --git a/.beads/hooks/prepare-commit-msg b/.beads/hooks/prepare-commit-msg
--- a/.beads/hooks/prepare-commit-msg
+++ b/.beads/hooks/prepare-commit-msg
@@ -63,12 +63,15 @@ call_lefthook()
     then
       devbox run lefthook "$@"
     else
-      echo "Can't find lefthook in PATH"
+      echo "Can't find lefthook in PATH" >&2
+      return 1
     fi
   fi
 }
 
 call_lefthook run "prepare-commit-msg" "$@"
+_lefthook_exit=$?
+if [ $_lefthook_exit -ne 0 ]; then exit $_lefthook_exit; fi
 
 # --- BEGIN BEADS INTEGRATION v0.62.0 ---
 # This section is managed by beads. Do not remove these markers.
